GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "Tessa Young",
    "name": "T",
    "password": "tessa",
    "blogs": []
}