DELETE https://whispering-journey-90122.herokuapp.com/api/persons/60dca421861cdb468c886065

###
DELETE http://localhost:3001/api/persons/60dcb7b812754b5960e80e87
###
GET https://whispering-journey-90122.herokuapp.com/api/persons/

###
POST https://whispering-journey-90122.herokuapp.com/api/persons
Content-Type: application/json 

{
    "name": "Baby Man",
    "number": "232-231-5676"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json 

{
    "name": "Leslie Odom",
    "number": "111-111-1111"
}

###
GET http://localhost:3001/api/man

###
PUT http://localhost:3001/api/persons/60dcbac8e95f3c524c62d7d4 HTTP/1.1
Content-Type: application/json

{
    "name": "John Tap",
    "number": "111-111-1111"
}